random: json11/json11.cpp random_choice.cpp
	g++ -O -std=c++11 json11/json11.cpp random_choice.cpp -o random_choice -fno-rtti -fno-exceptions

greedily: json11/json11.cpp greedily.cpp
	g++ -O -std=c++11 json11/json11.cpp greedily.cpp -o greedily -fno-rtti -fno-exceptions
